version: "3.8"
services:
  web:
    build: .
    container_name: api
    restart: always
    ports:
      - 8081:8080
    environment:
      DB_USER: root
      DB_NAME: test
      DB_PASSWORD:
      DB_HOST: mytestdb.ciqkdr.us-east-1.rds.amazonaws.com